Traceback (most recent call last):
  File "/home/nilomr/miniconda3/envs/pykanto-test/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/nilomr/miniconda3/envs/pykanto-test/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/nilomr/miniconda3/envs/pykanto-test/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/nilomr/miniconda3/envs/pykanto-test/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/nilomr/miniconda3/envs/pykanto-test/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/home/nilomr/miniconda3/envs/pykanto-test/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/nilomr/miniconda3/envs/pykanto-test/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/nilomr/miniconda3/envs/pykanto-test/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------

params = Parameters() # Using default parameters, which you should't
dataset = SongDataset(DATASET_ID, DIRS, parameters=params)
dataset.vocs.head()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileExistsError[0m                           Traceback (most recent call last)
Input [0;32mIn [3][0m, in [0;36m<module>[0;34m[0m
[1;32m      1[0m params [38;5;241m=[39m Parameters() [38;5;66;03m# Using default parameters, which you should't[39;00m
[0;32m----> 2[0m dataset [38;5;241m=[39m [43mSongDataset[49m[43m([49m[43mDATASET_ID[49m[43m,[49m[43m [49m[43mDIRS[49m[43m,[49m[43m [49m[43mparameters[49m[38;5;241;43m=[39;49m[43mparams[49m[43m)[49m
[1;32m      3[0m dataset[38;5;241m.[39mvocs[38;5;241m.[39mhead()

File [0;32m~/projects/pykanto/pykanto/dataset.py:117[0m, in [0;36mSongDataset.__init__[0;34m(self, DATASET_ID, DIRS, parameters, random_subset, overwrite_dataset, overwrite_data)[0m
[1;32m    115[0m [38;5;66;03m# Throw error if dataset already exists[39;00m
[1;32m    116[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mDIRS[38;5;241m.[39mDATASET[38;5;241m.[39mis_file() [38;5;129;01mand[39;00m overwrite_dataset [38;5;129;01mis[39;00m [38;5;28;01mFalse[39;00m:
[0;32m--> 117[0m     [38;5;28;01mraise[39;00m [38;5;167;01mFileExistsError[39;00m(
[1;32m    118[0m         [38;5;124mf[39m[38;5;124m'[39m[38;5;132;01m{[39;00mDATASET_ID[38;5;132;01m}[39;00m[38;5;124m already exists. You can overwrite [39m[38;5;124m'[39m
[1;32m    119[0m         [38;5;124m'[39m[38;5;124mit by setting `overwrite_dataset=True`[39m[38;5;124m'[39m)
[1;32m    121[0m [38;5;66;03m# Build dataset[39;00m
[1;32m    122[0m [38;5;28mself[39m[38;5;241m.[39m_get_wav_json_filedirs(random_subset[38;5;241m=[39mrandom_subset)

[0;31mFileExistsError[0m: GREAT_TIT already exists. You can overwrite it by setting `overwrite_dataset=True`
FileExistsError: GREAT_TIT already exists. You can overwrite it by setting `overwrite_dataset=True`

